### ISSUE TITLE
外网无法访问

### ISSUE THREAD

**Issue by lsdlh** [NolanHzy/nvjdcforwin#1]
程序跑起来没有监听在0.0.0.0，监听在127.0.0.1，外网无法访问

**Comment by NolanHzy** [comment]
自己用nginx代理一下

**Comment by lsdlh** [comment]
> 用自己的nginx代理一下

可以了用dotnet NETJDC.dll --urls=http://*:5000

**Comment by NolanHzy** [comment]
也行

**Comment by lsdlh** [comment]
dotnet NETJDC.dll --urls=http://*:5000
